name: receipt_scanner
description: Un'app Flutter per scansionare scontrini, estrarre testo e inviarli a Google Sheets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.0
  tesseract_ocr: ^0.3.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.6.0
  path_provider: ^2.1.2
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
