import 'dart:ui' show ImageFilter;
import 'package:flutter/material.dart';
import 'package:solducci/models/tag.dart';
import 'package:solducci/service/tag_service.dart';
import 'package:solducci/theme/todo_theme.dart';
import 'package:solducci/widgets/common/todo_app_bar.dart';

/// Dialog for creating or editing a tag
class TagFormDialog extends StatefulWidget {
  final Tag? tag; // null = create, non-null = edit

  const TagFormDialog({
    super.key,
    this.tag,
  });

  @override
  State<TagFormDialog> createState() => _TagFormDialogState();
}

class _TagFormDialogState extends State<TagFormDialog> {
  final _formKey = GlobalKey<FormState>();
  final _tagService = TagService();

  late TextEditingController _nameController;
  late TextEditingController _descriptionController;

  Color? _selectedColor;
  IconData? _selectedIcon;
  bool _showCompleted = false;
  bool _useAdvancedStates = false;
  bool _isLoading = false;

  // Predefined colors
  static const _availableColors = [
    Colors.red,
    Colors.pink,
    Colors.purple,
    Colors.deepPurple,
    Colors.indigo,
    Colors.blue,
    Colors.lightBlue,
    Colors.cyan,
    Colors.teal,
    Colors.green,
    Colors.lightGreen,
    Colors.lime,
    Colors.yellow,
    Colors.amber,
    Colors.orange,
    Colors.deepOrange,
    Colors.brown,
    Colors.grey,
    Colors.blueGrey,
  ];

  // Predefined icons
  static const _availableIcons = [
    Icons.label,
    Icons.work,
    Icons.home,
    Icons.shopping_cart,
    Icons.favorite,
    Icons.star,
    Icons.bookmark,
    Icons.lightbulb,
    Icons.fitness_center,
    Icons.school,
    Icons.computer,
    Icons.phone,
    Icons.email,
    Icons.calendar_today,
    Icons.attach_money,
    Icons.restaurant,
    Icons.local_cafe,
    Icons.directions_car,
    Icons.flight,
    Icons.hotel,
  ];

  @override
  void initState() {
    super.initState();

    // Initialize controllers
    _nameController = TextEditingController(text: widget.tag?.name ?? '');
    _descriptionController = TextEditingController(text: widget.tag?.description ?? '');

    // Initialize values for edit mode
    if (widget.tag != null) {
      _selectedColor = widget.tag!.colorObject;
      _selectedIcon = widget.tag!.iconData;
      _showCompleted = widget.tag!.showCompleted;
      _useAdvancedStates = widget.tag!.useAdvancedStates;
    } else {
      // Default values for new tag
      _selectedColor = TodoTheme.primaryPurple;
      _selectedIcon = Icons.label;
    }
  }

  /// Convert IconData to icon identifier string
  String? _iconDataToString(IconData? iconData) {
    if (iconData == null) return null;

    // Map of IconData to icon identifiers (reverse of Tag.iconData getter)
    final iconReverseMap = <int, String>{
      Icons.work.codePoint: 'work',
      Icons.home.codePoint: 'home',
      Icons.shopping_cart.codePoint: 'shopping',
      Icons.fitness_center.codePoint: 'fitness',
      Icons.local_hospital.codePoint: 'health',
      Icons.restaurant.codePoint: 'food',
      Icons.directions_car.codePoint: 'transport',
      Icons.school.codePoint: 'education',
      Icons.movie.codePoint: 'entertainment',
      Icons.family_restroom.codePoint: 'family',
      Icons.attach_money.codePoint: 'finance',
      Icons.flight.codePoint: 'travel',
      Icons.person.codePoint: 'personal',
      Icons.priority_high.codePoint: 'urgent',
      Icons.star.codePoint: 'star',
      Icons.flag.codePoint: 'flag',
      Icons.label.codePoint: 'label',
      Icons.folder.codePoint: 'folder',
      Icons.bookmark.codePoint: 'bookmark',
      Icons.favorite.codePoint: 'heart',
      Icons.check_circle.codePoint: 'check',
      Icons.calendar_today.codePoint: 'calendar',
      Icons.access_time.codePoint: 'clock',
      Icons.list.codePoint: 'list',
      Icons.lightbulb.codePoint: 'lightbulb',
      Icons.computer.codePoint: 'computer',
      Icons.phone.codePoint: 'phone',
      Icons.email.codePoint: 'email',
      Icons.local_cafe.codePoint: 'cafe',
      Icons.hotel.codePoint: 'hotel',
    };

    return iconReverseMap[iconData.codePoint];
  }

  /// Convert Color to hex string (without '#')
  String? _colorToHexString(Color? color) {
    if (color == null) return null;
    final argb = color.toARGB32();
    return argb.toRadixString(16).substring(2).toUpperCase();
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _saveTag() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final tag = Tag(
        id: widget.tag?.id ?? '', // Will be generated by service if empty
        userId: widget.tag?.userId ?? '', // Will be set by service
        name: _nameController.text.trim(),
        description: _descriptionController.text.trim().isEmpty
            ? null
            : _descriptionController.text.trim(),
        color: _colorToHexString(_selectedColor),
        icon: _iconDataToString(_selectedIcon),
        useAdvancedStates: _useAdvancedStates,
        showCompleted: _showCompleted,
        parentTagId: null, // Root tags for now
        createdAt: widget.tag?.createdAt ?? DateTime.now(),
        updatedAt: DateTime.now(),
      );

      if (widget.tag == null) {
        // Create new tag
        await _tagService.createTag(tag);
      } else {
        // Update existing tag
        await _tagService.updateTag(tag);
      }

      if (mounted) {
        Navigator.pop(context, true); // Return true to indicate success
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Errore: $e'),
            backgroundColor: Colors.red,
          ),
        );
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.transparent,
      child: Container(
        constraints: const BoxConstraints(maxWidth: 500, maxHeight: 700),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(16),
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
            child: Container(
              decoration: TodoTheme.glassDecoration(
                opacity: 0.05,
                borderOpacity: 0.5,
              ),
              child: Scaffold(
                backgroundColor: Colors.transparent,
                appBar: TodoAppBar(
                  title: widget.tag == null ? 'Nuovo Tag' : 'Modifica Tag',
                  leading: IconButton(
                    icon: const Icon(Icons.close),
                    color: TodoTheme.primaryPurple,
                    onPressed: () => Navigator.pop(context),
                  ),
                ),
                body: SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                  // Name field
                  TextFormField(
                    controller: _nameController,
                    decoration: const InputDecoration(
                      labelText: 'Nome *',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.title),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Inserisci un nome';
                      }
                      return null;
                    },
                    textCapitalization: TextCapitalization.sentences,
                  ),

                  const SizedBox(height: 16),

                  // Description field
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(
                      labelText: 'Descrizione',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.description),
                    ),
                    maxLines: 3,
                    textCapitalization: TextCapitalization.sentences,
                  ),

                  const SizedBox(height: 24),

                  // Color picker
                  const Text(
                    'Colore',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: _availableColors.map((color) {
                      final isSelected = _selectedColor?.toARGB32() == color.toARGB32();
                      return GestureDetector(
                        onTap: () => setState(() => _selectedColor = color),
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: BoxDecoration(
                            color: color,
                            shape: BoxShape.circle,
                            border: isSelected
                                ? Border.all(color: Colors.black, width: 3)
                                : null,
                          ),
                          child: isSelected
                              ? const Icon(Icons.check, color: Colors.white)
                              : null,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 24),

                  // Icon picker
                  const Text(
                    'Icona',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: _availableIcons.map((icon) {
                      final isSelected = _selectedIcon?.codePoint == icon.codePoint;
                      return GestureDetector(
                        onTap: () => setState(() => _selectedIcon = icon),
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: BoxDecoration(
                            color: isSelected
                                ? _selectedColor?.withValues(alpha: 0.2)
                                : Colors.grey[200],
                            borderRadius: BorderRadius.circular(8),
                            border: isSelected
                                ? Border.all(color: _selectedColor ?? TodoTheme.primaryPurple, width: 2)
                                : null,
                          ),
                          child: Icon(
                            icon,
                            color: isSelected ? _selectedColor : Colors.grey[600],
                          ),
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 24),

                  // Show completed toggle
                  SwitchListTile(
                    title: const Text('Mostra task completate'),
                    subtitle: const Text(
                      'Se attivo, la vista di questo tag mostrerà anche le task completate',
                    ),
                    value: _showCompleted,
                    onChanged: (value) => setState(() => _showCompleted = value),
                    activeColor: TodoTheme.primaryPurple,
                  ),

                  const SizedBox(height: 8),

                  // Use advanced states toggle
                  SwitchListTile(
                    title: const Text('Usa stati avanzati'),
                    subtitle: const Text(
                      'Abilita gli stati Assegnato e In Corso per le task di questo tag',
                    ),
                    value: _useAdvancedStates,
                    onChanged: (value) => setState(() => _useAdvancedStates = value),
                    activeColor: TodoTheme.primaryPurple,
                  ),
                      ],
                    ),
                  ),
                ),
                bottomNavigationBar: Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter,
                      colors: [
                        Colors.white.withValues(alpha: 0.1),
                        Colors.white.withValues(alpha: 0.05),
                      ],
                    ),
                    border: Border(
                      top: BorderSide(
                        color: Colors.white.withValues(alpha: 0.3),
                        width: 1,
                      ),
                    ),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      TextButton(
                        onPressed: _isLoading ? null : () => Navigator.pop(context),
                        child: const Text('Annulla'),
                      ),
                      const SizedBox(width: 8),
                      ElevatedButton(
                        onPressed: _isLoading ? null : _saveTag,
                        style: TodoTheme.elevatedButtonStyle,
                        child: _isLoading
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : Text(widget.tag == null ? 'Crea' : 'Salva'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
